version: '3.4'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: scram_local_django
    depends_on:
      - postgres
    volumes:
      - $CI_PROJECT_DIR:/app:z
      - /tmp/profile_data:/tmp/profile_data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000"
    command: /start
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://django:8000/process_expired/" ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 5

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: scram_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0
    ports:
      - "6379"

  gobgp:
    image: jauderho/gobgp:v2.32.0
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"

  translator:
    build:
      context: .
      dockerfile: ./compose/local/translator/Dockerfile
    depends_on:
      - gobgp
